// poc/identity/app/src/screens/Phase1.tsx
import { useState } from 'react';
import { Text, View } from 'react-native';
import { Api, ApiError, Phase1Account, Variant } from '../api';
import { Theme } from '../theme';
import { Button, Card, Field, KeyValue, Notice, s } from '../ui';

/** The Phase 1 login the apps fall back to while F3 is switched off (plan task 2.10). */
export function Phase1Login({ api, variant, theme }: { api: Api; variant: Variant; theme: Theme }) {
  const [identifier, setIdentifier] = useState('');
  const [password, setPassword] = useState('');
  const [account, setAccount] = useState<Phase1Account | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const signIn = async () => {
    setBusy(true);
    setError(null);
    try {
      setAccount(await api.phase1Login(identifier, password));
    } catch (e) {
      setError(e instanceof ApiError ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <View>
      <Notice tone="warn" title="Shared Identity is switched off">
        This app is using the Phase 1 login. Accounts are separate per app. Nothing created with Shared Identity has been lost: switch it
        back on and everyone signs in as before.
      </Notice>
      {account ? (
        <Card title={`Phase 1 ${variant === 'partner' ? 'partner' : 'user'} account`}>
          <Text style={s.h1}>{account.businessName ?? account.name}</Text>
          <KeyValue k="Phase 1 account #" v={String(account.legacyId)} />
          {account.businessName && <KeyValue k="Owner" v={account.name} />}
          {account.partnerType && <KeyValue k="Partner type" v={account.partnerType} />}
          {account.kycStatus && <KeyValue k="KYC" v={account.kycStatus} />}
          <View style={{ marginTop: 12 }}>
            <Button label="Sign out" kind="ghost" theme={theme} onPress={() => setAccount(null)} />
          </View>
        </Card>
      ) : (
        <Card>
          <Text style={s.h1}>Sign in</Text>
          <Text style={[s.muted, { marginBottom: 16 }]}>Phase 1 demo accounts use the password demo1234.</Text>
          <Field
            label="Mobile number or email"
            placeholder={variant === 'partner' ? '98765 43210' : '98123 45678'}
            value={identifier}
            onChangeText={setIdentifier}
          />
          <Field label="Password" secureTextEntry value={password} onChangeText={setPassword} onSubmitEditing={signIn} />
          {error && <Notice tone="danger">{error}</Notice>}
          <Button label="Sign in" theme={theme} busy={busy} onPress={signIn} disabled={!identifier || !password} />
        </Card>
      )}
    </View>
  );
}

export function UpdateRequired({ theme, min, current }: { theme: Theme; min: string; current: string }) {
  return (
    <Card>
      <Text style={{ fontSize: 44, textAlign: 'center', marginBottom: 8 }}>⬆️</Text>
      <Text style={[s.h1, { textAlign: 'center' }]}>Update required</Text>
      <Text style={[s.body, { textAlign: 'center', marginVertical: 12 }]}>
        This version ({current}) is no longer supported. Please update to {min} or later to keep using {theme.name}.
      </Text>
      <Text style={[s.muted, { textAlign: 'center' }]}>
        Minimum-version enforcement: the API also answers 426 to this build, so old apps in the field cannot call changed APIs.
      </Text>
    </Card>
  );
}

// poc/identity/web-lit/src/phase1.js
import { LitElement, html, nothing } from 'lit';
import { ApiError } from './api.js';
import { base } from './shared.js';

/** The Phase 1 login the apps fall back to while Shared Identity is switched off. */
export class SsPhase1 extends LitElement {
  static properties = {
    api: { attribute: false },
    variant: {},
    _identifier: { state: true },
    _password: { state: true },
    _account: { state: true },
    _error: { state: true },
    _busy: { state: true },
  };

  static styles = base;

  constructor() {
    super();
    this._identifier = '';
    this._password = '';
    this._account = null;
    this._error = null;
    this._busy = false;
  }

  async _signIn() {
    this._busy = true;
    this._error = null;
    try {
      this._account = await this.api.phase1Login(this._identifier, this._password);
    } catch (e) {
      this._error = e instanceof ApiError ? e.message : String(e);
    } finally {
      this._busy = false;
    }
  }

  render() {
    const a = this._account;
    return html`<div class="stack">
      <div class="notice warn rise">
        <b>Shared Identity is switched off</b>This app is using the Phase 1 login, with separate accounts per app. Nothing created with Shared
        Identity is lost: switch it back on and everyone signs in as before.
      </div>
      ${a
        ? html`<div class="card stack">
            <span class="eyebrow">Phase 1 ${this.variant === 'partner' ? 'partner' : 'user'} account</span>
            <h1>${a.businessName ?? a.name}</h1>
            <div>
              <div class="kv"><span>Phase 1 account</span><span>#${a.legacyId}</span></div>
              ${a.businessName ? html`<div class="kv"><span>Owner</span><span>${a.name}</span></div>` : nothing}
              ${a.partnerType ? html`<div class="kv"><span>Partner type</span><span>${a.partnerType}</span></div>` : nothing}
              ${a.kycStatus ? html`<div class="kv"><span>KYC</span><span>${a.kycStatus}</span></div>` : nothing}
            </div>
            <button class="btn ghost" @click=${() => (this._account = null)}>Sign out</button>
          </div>`
        : html`<div class="card stack">
            <h1>Sign in</h1>
            <p class="muted">Phase 1 demo accounts use the password <span class="mono">demo1234</span>.</p>
            <label class="field"
              >Mobile number or email
              <input
                id="p1-id-${this.variant}"
                placeholder=${this.variant === 'partner' ? '98765 43210' : '98123 45678'}
                .value=${this._identifier}
                @input=${(e) => (this._identifier = e.target.value)}
            /></label>
            <label class="field"
              >Password
              <input
                id="p1-pw-${this.variant}"
                type="password"
                .value=${this._password}
                @input=${(e) => (this._password = e.target.value)}
                @keydown=${(e) => e.key === 'Enter' && this._signIn()}
            /></label>
            ${this._error ? html`<div class="notice danger" role="alert">${this._error}</div>` : nothing}
            <button class="btn" ?disabled=${!this._identifier || !this._password || this._busy} @click=${() => this._signIn()}>
              ${this._busy ? 'Signing in…' : 'Sign in'}
            </button>
          </div>`}
    </div>`;
  }
}
customElements.define('ss-phase1', SsPhase1);
